### ISSUE TITLE
no powermail form selection possible (TYPO3 11.5.37, powermail v10.8.1 and PHP 8.2)

### ISSUE THREAD

**Issue by medarob** [in2code-de/powermail#1043]
When I use the powermail plugin as an inline field, for example in mask, I can't select any of the existing powermail forms. That's leads to the problem, that I can't update the settings of the plugin because saving the element doesn't work.

![grafik](https://github.com/in2code-de/powermail/assets/33951787/7685e84e-8d9a-4516-bf22-7b5188574972)

This is the error message in the BE:

**Bei dem Versuch, die Elemente für Feld "Powermail Formular wählen" (PHP Warning: Undefined array key "query" in /var/www/typo3_web-dev2/public/typo3conf/ext/powermail/Classes/Utility/BackendUtility.php line 193) zu verarbeiten, ist ein Fehler aufgetreten.**

![grafik](https://github.com/in2code-de/powermail/assets/33951787/1c9f1dfa-9bed-4f53-b8b7-ca021fd62d81)

This happens with PHP 8.2.19.
It works with PHP 7.4.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
This is already fixed in https://github.com/in2code-de/powermail/commit/36803943d77202d4449463bf4f22bd259d96e163 for since Powermail 11.0.0. There was no backport to Powermail 10, so I recommend the following:

1. Patch it yourself.  It's easy and only 1 line you'll need to add.
2. Update server to PHP 8
3. Update to TYPO3 12 and Powermail 12 at the same time

**Comment by mschwemer** [comment]
Won't backport it as TYPO3 v11 is already in ELTS. 

I agree with the recommendation to patch it yourself. 

If you need it in an official version, you can get paid support via https://www.in2code.de/en/contact/ and we will make a new release for it.
