### ISSUE TITLE
Empty response (204) with multiple plugins on the same page from v12.3.2 and onward

### ISSUE THREAD

**Issue by Phosphenius** [in2code-de/powermail#1052]
PHP: 8.1
TYPO3: 12.4.15

When there are more than one pi1 Plugins on the same page, submitting a form causes an empty response (204) and the form success message is not shown. Furthermore, when AJAX submit is enabled, the form is submitted twice. Emails are still sent though. 

I've tracked this down to the introduction of the `checkCreateAction` which was introduced in 12.3.2.

Like already said, this issue only occurs when there is more than one active plugin on the same page. A single plugin works just fine.

Here's a list of versions I tested:

- 12.3.5 [broken]
- 12.3.4 [broken]
- 12.3.2 [broken] (culprit!)
- 12.3.1 [works]
- 12.3.0 [not tested]
- 12.2.1 [works]
- 12.2.0 [not tested]
- 12.1.1 [not tested]
- 12.1.0 [not tested]                                                                                 
- 12.0.3 [works] 

Unfortunately, I haven't been able to figure out a fix yet.

**Comment by instruccionesaldorso** [comment]
I can confirm this behaviour.
I've downgraded to 12.3.1 version for now.

**Comment by sitsCHO** [comment]
I can confirm this behavior to, 

I just want to add that just the first plugin is sending e-mails, all following plugins on the page do not.

**Comment by MohsinQK** [comment]
I can also confirm.
TYPO3 v12.4.17
Powermail v12.3.5

**Comment by w010** [comment]
I get the same, and now also in many situations, even when I removed second forms, now it just reloads page and I have status 200 and no submit, no error, no validation, nothing. I can't trace what is causing the situation, some caching issues or what. And I need to rollout the project this week

**Comment by andrii-kshanovskyi** [comment]
A new method was added - `initializeCheckCreateAction` - it checks whether Mail param is empty and also if the uid of a requested form matches the form uids in flexform. If not, it forwards to `form` action. For some reason, it loads only uid of the first form of all dynamic forms, that's why it works and others don't. A possible but temporary solution is to override the method and remove the check.

**Comment by sitsCHO** [comment]
Hi, can anyone tell me if this Problem still exists in v 12.4.1 ?

**Comment by instruccionesaldorso** [comment]
@sitsCHO I can confirm this is still happening in **EXT:powermail** version **12.4.1.** with latest TYPO3 12.4.20 version.
Those who had to downgrade to 12.3.1 version due to this issue, now we're in a dead end corner, as we're forced to upgrade to 12.4.1 due to insecurity issue published this week :-(

**Comment by mschwemer** [comment]
I rolled back the commit that lead to this behavior. 

The rollback is included in the latest release 12.4.2.
