### ISSUE TITLE
different validation of urls in JavaScript and PHP

### ISSUE THREAD

**Issue by lisardo2** [in2code-de/powermail#511]
The javascript validation of a valid url allows url with or without protocol: 

all the following urls are valid: 
- http://www.domain.de
- https://www.domain.de
- www.domain.de 

But the validation via php throws an error with "www.domain.de". 

The reason is a change in behavior since php 5.2.1. 

up to php 5.2.1 FILTER_VALIDATE_URL allows urls with or without protocol but from PHP 5.2.1 FILTER_VALIDATE_URL uses implicit FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED. 

/Classes/Domain/Validator/StringValidator.php line 42 - 45. 
https://www.php.net/manual/de/filter.filters.validate.php (changelog)

It seems there is no way to disable the use of FILTER_FLAG_SCHEME_REQUIRED: 
https://stackoverflow.com/questions/45240033/what-is-use-of-filter-flag-scheme-required-and-filter-flag-host-required-flags-f

--

So the only way to fix this misbahavior ist to add a test for the protocol to the javascript.

**Comment by einpraegsam** [comment]
You could check if parsley allows such an option in a newer version: http://parsleyjs.org/

**Comment by eBornstein** [comment]
This is still a problem.
PHP throws error without https://, powermail doesnt.

TYPO3 12.4.15
powermail 12.3.1
PHP 8.1

**Comment by mschwemer** [comment]
I can confirm this behaviour. But this is not a bug, but an intended behaviour.  

Using a pattern in general would be bad idea, because this has drawbacks: 

Not only `https` is a valid protocol. There are many out there: `ssh`, `ftp`, `sftp`, `rsync`, ... If you need to force a protocol, you can overwrite the partial for the input field and require it there. Furthermore, you should give the users a hint, which protocol they must use (title, placeholder). 
 
If we do not check for a protocol, it would be just a plain string and for example like `localhost` or `my-nice-local-server` are also correct URLs.  Then it would be a plain string. In this case, I would recommend to use this type and add a proper description. 

Hope that helps.
