### ISSUE TITLE
validation by regex works client side (JS), but not server side

### ISSUE THREAD

**Issue by derBoogie** [in2code-de/powermail#528]
Hi,
I have an problem with the validation of a password field with the following regex:
`/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W])[a-zA-Z0-9\S]{8,}$/`
-> rule: min. 8 characters, a small and a capital character, a number, a special character
It works client side (JS) but not serverside.
(TYPO3 9.5, Powermail 7.4.0)

Can someone test and confirm that?

Thanks!

**Comment by mtness** [comment]
Yes, I can confirm that regex pattern validation does not seem to work, when ther is a unicode range included, like: `^[A-Za-z\-\_\,\.\s**\u00c0-\u1f0f**]+$` 
without that, it seems to work^^

**Comment by Hawkeye1909** [comment]
I can confirm at least the problem with unicode ranges. The cause is that regular expressions for JavaScript and PHP/ PCRE are not completely compatible. So either a converter (not sure if that's even possible for all cases but here's something I've found: https://github.com/TooTallNate/pcre-to-regexp) would be needed or the possibility to enter an optional server regex (which would be a lot easier to implement...).

**Comment by mschwemer** [comment]
Cannot confirm this issue any more. Please not that the `/` are not allowed in the regex field.

Tested with the latest powermail release and php 8.1
