### ISSUE TITLE
Registering at Garbage Collection task must happen in ext_localconf (not in ext_tables)

### ISSUE THREAD

**Issue by foobar13372** [in2code-de/powermail#718]
This happens currently in `ext_tables.php` of `ext:powermail`

```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['scheduler']['tasks'][$tgct]['options']['tables'][$table] = [
    'dateField' => 'tstamp',
    'expirePeriod' => 30
];
```

This MUST happen in `ext_localconf`, if you strictly follow TYPO3 core guidelines!

**Comment by einpraegsam** [comment]
Thank you for the clarification. I keep this issue open for the moment. 
Current developments are focused on TYPO3 11 updates.

**Comment by mschwemer** [comment]
I will not change this, since many other users probably rely on this place. 

I checked the TYPO3 core docs beginning version 10 up to the current main (v13). https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtTables.html

Each version says, that `ext_tables` should be used for registering scheduler tasks (including a link to the example). 

AFAIK sooner or later `ext_tables.php` will become obsolete. Then we will change that too.
