### ISSUE TITLE
No error message despite wrong smtp data

### ISSUE THREAD

**Issue by s-thierock** [in2code-de/powermail#812]
When I submit a form, my success message appears on the submit page, although the SMTP data is incorrect and no email is sent. No error message is displayed either in the frontend or in the backend log.

The powermail function check in the backend correctly throws an error.

Tested in these setups:
- TYPO3 10.4.32 + powermail 8.4.2
- TYPO3 11.5.15 + powermail 10.4.3

**Comment by mschwemer** [comment]
That's the reason why the checks are there, in the `Admin Tools -> Environment` from the core and the test by powermail. It is the job of the integrator to make that save. 

Another reason, why we do not output an error message is, because sending mail is the last step. Via the BE the sent email is saved correctly and accessible by the editors.
