### ISSUE TITLE
Export link is given to pagination links

### ISSUE THREAD

**Issue by spoonerWeb** [in2code-de/powermail#903]
If you do an export in the mail list backend module and click onto the pagination link, the export starts again.

Reproduce:

1. Go to Backend module -> Mail List
2. Be sure to have minimum 2 pages of results
3. Click on CSV export -> export starts
4. Click on another page -> export starts again

Powermail: 10.7.2
TYPO3: 11.5.30
PHP: 7.4.33

**Comment by psternuva** [comment]
Can confirm with Powermail 10.7.4.

Bug also happens with the XLS export button.

The export buttons are implemented with Javsacript as far as I can tell, with then interferers with the pagination links.

**Comment by psternuva** [comment]
@mschwemer @spoonerWeb 

Having a quick look at the code here: https://github.com/in2code-de/powermail/blob/develop/Resources/Private/Build/JavaScript/Backend.js

I think it's need to add **after** line # 45 (  `('form').submit(); `)

   `$('#forwardToAction').val('list');`

Otherwise the forward to action is 'stuck' with the export action.

I have however not tested this.

**Comment by mschwemer** [comment]
Fixed with a6f71a45846cd8bb587beff31496601e7b01c718
